# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build Sphinx documentation & Run unittest
on: [push]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Sphinx
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
      - name: Test
        uses: onichandame/python-test-action@master
        with:
          python-version: '3.7'
          deps_list: 'requirements.txt'
